

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import static javax.swing.JOptionPane.showMessageDialog;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Erick
 */
public class agregarExp extends javax.swing.JFrame {
    private Paciente paciente;
    private medico medico;
    private Connection con;
    /**
     * Creates new form agregarExp
     */
    public agregarExp(Paciente paciente, medico medico) {
        con = ConexionSQL.ConexionSQLServer();
        this.paciente = paciente;
        this.medico = medico;
        initComponents();
        rellenarEtiquetas(paciente.getNss());
        this.setLocationRelativeTo(null);
        insertarIdDelExpediente();
        
        txtFrecResp.setSize(64, 22);
        txtPresArt.setSize(64, 22);
        txtFrecCardiaca.setSize(64, 22);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        lblActualizar = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        reloj11 = new Reloj1();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblAp2 = new javax.swing.JLabel();
        lblAp1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFecNac = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbTemp = new javax.swing.JComboBox<>();
        txtFrecResp = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtPresArt = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFrecCardiaca = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        lblGuardar = new javax.swing.JLabel();
        lblCancelar = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblidExp = new javax.swing.JLabel();
        lblIdenExp = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtFrecCardiaca2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(136, 212, 234));

        lblSalir.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesionM.png"))); // NOI18N
        lblSalir.setText("Cerrar sesión");
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        lblAtras.setFont(new java.awt.Font("Roboto", 2, 22)); // NOI18N
        lblAtras.setIcon(new javax.swing.ImageIcon("C:\\CIC\\loginHospital\\src\\imagenes\\flecha-izquierda (3).png")); // NOI18N
        lblAtras.setText("Atrás");
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });

        lblActualizar.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        lblActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar-datos.png"))); // NOI18N
        lblActualizar.setText("Actualizar expediente");
        lblActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblActualizarMouseClicked(evt);
            }
        });

        lblUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo .png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblUsuario1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalir)
                    .addComponent(lblActualizar)
                    .addComponent(lblAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblUsuario1)
                .addGap(165, 165, 165)
                .addComponent(lblActualizar)
                .addGap(90, 90, 90)
                .addComponent(lblAtras)
                .addGap(153, 153, 153)
                .addComponent(lblSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reloj11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Datos del paciente");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("Apellido Paterno");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setText("Apellido materno");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNombre.setText("jLabel5");

        lblAp2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAp2.setText("jLabel6");

        lblAp1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAp1.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel8.setText("Fecha de nacimiento");

        lblFecNac.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFecNac.setText("jLabel9");
        lblFecNac.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel12.setText("Signos vitales");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel13.setText("Temperatura");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel14.setText("Frecuencia respiratoria");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel15.setText("Presión arterial");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel16.setText("Frecuencia cardiaca");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel17.setText("Motivo de atención");

        cmbTemp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona unidad de medida...", "Hipotermia ", "32 °C", "33 °C", "34 °C", "35 °C", "36 °C", "37 °C", "38 °C", "39 °C", "40 °C", "Hipertermia severa" }));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel18.setText("RPM");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("mmHg");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("LPM");

        txtMotivo.setColumns(20);
        txtMotivo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMotivo.setRows(5);
        jScrollPane1.setViewportView(txtMotivo);

        lblGuardar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/disco-flexibleM.png"))); // NOI18N
        lblGuardar.setText("Guardar");
        lblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGuardarMouseClicked(evt);
            }
        });

        lblCancelar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblCancelar.setIcon(new javax.swing.ImageIcon("C:\\CIC\\loginHospital\\src\\imagenes\\boton-eliminar.png")); // NOI18N
        lblCancelar.setText("Cancelar");

        lblAgregar.setFont(new java.awt.Font("Roboto", 3, 22)); // NOI18N
        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        lblAgregar.setText("Agregar expediente");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel10.setText("Edad");

        lblEdad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEdad.setText("jLabel9");
        lblEdad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblidExp.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        lblidExp.setText("idExpediente");

        lblIdenExp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblIdenExp.setText("jLabel6");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(lblGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCancelar)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reloj11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblNombre)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(lblAp1))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblFecNac)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(216, 216, 216)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblAp2)
                                                            .addComponent(jLabel4))
                                                        .addGap(52, 52, 52))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(lblAgregar)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(jLabel10)
                                                                    .addComponent(jLabel1))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(lblEdad))))))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel13)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cmbTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel14)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtFrecResp, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addGap(71, 71, 71)
                                                    .addComponent(jLabel3))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtFrecCardiaca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel21)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtFrecCardiaca2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jLabel20))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtPresArt, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(jLabel19)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblidExp)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblIdenExp))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(jLabel17))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(jLabel12)))
                        .addContainerGap(282, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reloj11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgregar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidExp)
                    .addComponent(lblIdenExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblAp2)
                    .addComponent(lblAp1))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblFecNac)
                    .addComponent(jLabel10)
                    .addComponent(lblEdad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFrecResp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel14))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPresArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtFrecCardiaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(txtFrecCardiaca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGuardar)
                    .addComponent(lblCancelar))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        loginHospitalNuevo hl = new loginHospitalNuevo();
        hl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        this.dispose();
        expMed em = new expMed(this.paciente, this.medico);
        em.setVisible(true);
        //revisar que este mande al expediente medico
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblActualizarMouseClicked
        act_eli_Expediente aee = new act_eli_Expediente(this.medico);
        this.setVisible(false);
        aee.setVisible(true);
    }//GEN-LAST:event_lblActualizarMouseClicked

    private void lblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGuardarMouseClicked
        
        Statement st; 
        String fecha = "";
        
        String temp = cmbTemp.getSelectedItem().toString();
        
        LocalDateTime hoy = LocalDateTime.now();
        fecha = hoy.getYear()+"-"+hoy.getMonthValue()+"-"+hoy.getDayOfMonth();
        
        
        String queryGuardar="insert into expediente_clinico\n" +
                            "values ('"+this.medico.getIdMedico()+"','"+this.paciente.getNss()+"', '"+temp+"','"+txtFrecResp.getText()+"', '"+txtPresArt.getText()+"',\n"
                            + "'"+txtFrecCardiaca.getText()+"/"+txtFrecCardiaca2.getText()+"', '"+txtMotivo.getText()+"', '"+fecha+"') ";
        
        try{
            st = con.createStatement();
            st.executeUpdate(queryGuardar);
            showMessageDialog(null,"Exito al insertar expediente médico");
        }catch(SQLException e){
            System.out.println(e.getMessage()+"  AQUI ESTA EL ERROR");
        }
        
        cmbTemp.setSelectedIndex(0);
        txtFrecResp.setText("");
        txtPresArt.setText("");
        txtFrecCardiaca.setText("");
        txtMotivo.setText("");
        cmbTemp.setSelectedIndex(0);
    }//GEN-LAST:event_lblGuardarMouseClicked
    
    private void insertarIdDelExpediente(){
        ResultSet rs;
        Statement st;
        int ultimoExp=0;
        

        String query = "SELECT TOP 1 idExp FROM expediente_clinico ORDER BY idExp DESC;";
        String idExp = "EXP-";
        
        try{
            st = con.createStatement();
            rs= st.executeQuery(query);
            while(rs.next()){
                System.out.println("El ultimo pendejo valor del idExpediente: "+rs.getString("idExp"));
                ultimoExp=rs.getInt("idExp")+1;
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        idExp = idExp+ultimoExp;
        lblIdenExp.setText(idExp);
        System.out.println("Ultimo id exp: "+idExp);
    }
    
    private String obtenerIdMed(String usuarioId){
        con = ConexionSQL.ConexionSQLServer();
        Statement stmt2;
        ResultSet resultadoMed;
        String identificadorMed = "";

        try {
            stmt2 = con.createStatement();
            String idMed = "select med.idMedico \n"
                    + "from medico med\n"
                    + "inner join usuario u on (med.Correo = u.correo)\n"
                    + "where med.Correo = " + "'" + usuarioId + "'";

            resultadoMed = stmt2.executeQuery(idMed);

            while (resultadoMed.next()) {
                identificadorMed = resultadoMed.getString("idMedico");
            }

        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return identificadorMed;
    }
    
    private void rellenarEtiquetas(String ns){
        ResultSet rs;
        Statement st;
    
        String q = "select pac.nombrePac, pac.apellido1, pac.apellido2,  pac.fechaNac\n" +
                    "from paciente pac\n"+
                    "WHERE pac.numeroSeguro = '"+ns+"'";
        
        String nombre="", apellido1="", apellido2="", fecNac="";
        
        int ed=0,aa=0;

        
        try{
            st = con.createStatement();
            rs= st.executeQuery(q);
            while(rs.next()){
                nombre=rs.getString("nombrePac");
                apellido1=rs.getString("apellido1");
                apellido2=rs.getString("apellido2");
                fecNac=rs.getString("fechaNac");
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }        
                lblNombre.setText(nombre);
                lblAp1.setText(apellido1);
                lblAp2.setText(apellido2);
                lblFecNac.setText(fecNac);
                lblEdad.setText(expMed.obtenerEdadReal(fecNac)+"");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarExp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                agregarExp ae = new agregarExp(ventanaCitasMed.getPaciente(),ventanaMedico.getMedico());
                ae.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblActualizar;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblAp1;
    private javax.swing.JLabel lblAp2;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCancelar;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblFecNac;
    private javax.swing.JLabel lblGuardar;
    private javax.swing.JLabel lblIdenExp;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblidExp;
    private Reloj1 reloj11;
    private javax.swing.JTextField txtFrecCardiaca;
    private javax.swing.JTextField txtFrecCardiaca2;
    private javax.swing.JTextField txtFrecResp;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextField txtPresArt;
    // End of variables declaration//GEN-END:variables
}
