
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.Date;

/**
 *
 * @author Erick
 */
public class expMed extends javax.swing.JFrame {
    
    private Paciente paciente;
    private medico medico;
    private Connection con;
    /**
     * Creates new form expMed
     */
    public expMed(Paciente paciente, medico medico) {
        con = ConexionSQL.ConexionSQLServer();
        setSize(1200,800);
        this.setLocationRelativeTo(null);
        this.paciente = paciente;
        this.medico=medico;
        initComponents();
        this.setLocationRelativeTo(null);
        rellenarEtiquetas(paciente.getNss());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        lblConsultarExp = new javax.swing.JLabel();
        noName = new javax.swing.JLabel();
        reloj11 = new Reloj1();
        lblNss = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblEmergencia = new javax.swing.JLabel();
        lblCronica = new javax.swing.JLabel();
        lblFamilia = new javax.swing.JLabel();
        lblAlcohol = new javax.swing.JLabel();
        lblTabaco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(136, 212, 234));

        lblSalir.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-sesionM.png"))); // NOI18N
        lblSalir.setText("Cerrar sesión");
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });

        lblAtras.setFont(new java.awt.Font("Roboto", 2, 22)); // NOI18N
        lblAtras.setIcon(new javax.swing.ImageIcon("C:\\CIC\\loginHospital\\src\\imagenes\\flecha-izquierda (3).png")); // NOI18N
        lblAtras.setText("Atrás");
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });

        lblAgregar.setFont(new java.awt.Font("Roboto", 2, 24)); // NOI18N
        lblAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir.png"))); // NOI18N
        lblAgregar.setText("Agregar expediente");
        lblAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAgregarMouseEntered(evt);
            }
        });

        lblUsuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo .png"))); // NOI18N

        lblConsultarExp.setFont(new java.awt.Font("Roboto", 2, 22)); // NOI18N
        lblConsultarExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pregunta.png"))); // NOI18N
        lblConsultarExp.setText("Consultar expediente");
        lblConsultarExp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblConsultarExpMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblUsuario1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalir)
                    .addComponent(lblAgregar)
                    .addComponent(lblConsultarExp)
                    .addComponent(lblAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblUsuario1)
                .addGap(90, 90, 90)
                .addComponent(lblAgregar)
                .addGap(84, 84, 84)
                .addComponent(lblConsultarExp)
                .addGap(92, 92, 92)
                .addComponent(lblAtras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lblSalir)
                .addGap(58, 58, 58))
        );

        noName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/documentacionPaciente.png"))); // NOI18N
        noName.setText("Expediente");

        reloj11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lblNss.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNss.setText("jLabel7");

        lblEdad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEdad.setText("jLabel8");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel5.setText("Datos principales del paciente");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel2.setText("Apellidos:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel3.setText("NSS:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel4.setText("Edad:");

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNombre.setText("jLabel5");

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblApellidos.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel6.setText("Contacto de emergencia:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel8.setText("Enfermedad crónica:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel9.setText("Familiares con enfermedad:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel10.setText("Consumo de tabaco");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel11.setText("Consumo de alcohol:");

        lblEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblEmergencia.setText("jLabel12");

        lblCronica.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCronica.setText("jLabel12");

        lblFamilia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblFamilia.setText("jLabel12");

        lblAlcohol.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblAlcohol.setText("jLabel12");

        lblTabaco.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTabaco.setText("jLabel12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(lblFamilia))
                                .addComponent(lblTabaco, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblAlcohol, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCronica, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEmergencia, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNss, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noName, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(reloj11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reloj11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noName))
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblApellidos))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblNss))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblEdad))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblEmergencia))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblCronica))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblFamilia))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTabaco))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblAlcohol))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        loginHospitalNuevo hl = new loginHospitalNuevo();
        hl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        this.dispose();
        
    }//GEN-LAST:event_lblAtrasMouseClicked

    private void lblAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseClicked
        agregarExp ae = new agregarExp(this.paciente, this.medico);
        ae.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAgregarMouseClicked
    
    public static int obtenerEdadReal(String fecNac){
        int edadReal=0;
        Date fechaAct= new Date();
        
        int years, mes, dia, aNac, mNac, dNac;
        //2000-02-04
        aNac = Integer.parseInt(fecNac.substring(0,4));
        mNac = Integer.parseInt(fecNac.substring(5,7));
        dNac = Integer.parseInt(fecNac.substring(8,10));
        LocalDateTime act  = LocalDateTime.now();
        
        years = act.getYear();
        mes = act.getMonth().getValue();
        dia = act.getDayOfMonth();
        
        System.out.println("Datos actuales:"+years+"-"+mes+"-"+dia);
        System.out.println("Datos de nacimiento:"+aNac+"-"+mNac+"-"+dNac);
        
        if((mNac<mes)&&(dNac<dia)){
            edadReal=years-aNac;
        }else{
            edadReal=(years-aNac)-1;
        }
        return edadReal;
    }
    
    private void lblConsultarExpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblConsultarExpMouseClicked
        Expediente_elegido ee = new Expediente_elegido(this.paciente, this.medico);
        this.setVisible(false);
        ee.setVisible(true);
    }//GEN-LAST:event_lblConsultarExpMouseClicked

    private void lblAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAgregarMouseEntered
    
    private void rellenarEtiquetas(String nss){
        ResultSet rs;
        Statement st;
    
        String q = "select pac.nombrePac, pac.apellido1, pac.apellido2,  pac.fechaNac,pac.numeroSeguro, \n" +
                    "pp.Contacto_Emergencia, pp.enfermedad_cronica, pp.tabaco, pp.alcohol, pp.Enfermedad_familiar\n" +
                    "from paciente pac\n" +
                    "inner join preguntas_preliminares pp on (pac.numeroSeguro = pp.nss)\n"+
                    "WHERE pac.numeroSeguro = '"+nss+"'";
        
        String nombre="", apellido1="", apellido2="", nss2="", edad="", emergencia="", cronica="", familia="", tabaco="", alcohol="";
        int ed=0,aa=0;
        
        LocalDateTime hoy = LocalDateTime.now();
        aa = hoy.getYear();
        
        try{
            st = con.createStatement();
            rs= st.executeQuery(q);
            while(rs.next()){
                nombre=rs.getString("nombrePac");
                apellido1=rs.getString("apellido1");
                apellido2=rs.getString("apellido2");
                edad=rs.getString("fechaNac");
                nss2=rs.getString("numeroSeguro");
                emergencia=rs.getString("contacto_Emergencia");
                cronica=rs.getString("enfermedad_Cronica");
                tabaco=rs.getString("tabaco");
                alcohol=rs.getString("alcohol");
                familia=rs.getString("enfermedad_Familiar");
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }       
                ed = aa - (Integer.parseInt(edad.substring(0,4)));
                
                lblNombre.setText(nombre);
                lblNss.setText(nss2);
                lblApellidos.setText(apellido1 + " "+apellido2);
                lblEdad.setText(obtenerEdadReal(edad)+"");
                lblNss.setText(nss2);
                lblEmergencia.setText(emergencia);
                lblCronica.setText(cronica);
                lblFamilia.setText(familia);
                lblTabaco.setText(tabaco);
                lblAlcohol.setText(alcohol);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(expMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(expMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(expMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(expMed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                expMed em = new expMed(ventanaCitasMed.getPaciente(), ventanaMedico.getMedico());
                em.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblAlcohol;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblConsultarExp;
    private javax.swing.JLabel lblCronica;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmergencia;
    private javax.swing.JLabel lblFamilia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNss;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTabaco;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel noName;
    private Reloj1 reloj11;
    // End of variables declaration//GEN-END:variables
}
